spring:
  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      uri: mongodb+srv://anup21panchal_db_user:74e4LAv7rbXgljCo@cluster0.4hwhfiy.mongodb.net/hotel-db?retryWrites=true&w=majority&appName=Cluster0

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-1tbxzi5afsy5e1pd.us.auth0.com/

  mail:
    host: smtp.gmail.com
    port: 587
    username: anup21panchal@gmail.com
    password: mrjf fopa sjck ylro
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# application-level settings
support:
  email:
    to: tempsacwork@yahoo.com

# prefix used to build confirmation URL in NotificationService
app:
  frontend:
    confirm-url-prefix: http://localhost:8080/api/auth/confirm?token=


logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.hotel.hotel_booking_service